repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: ^tests/data/

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: ^tests/data/.*$

  - repo: https://github.com/PyCQA/flake8
    rev: ''
    hooks:
      - id: flake8
        name: flake8
        args:
          - --max-line-length=120
          - --exit-zero
        exclude: ^tests/data/
