version: '3.8'
services:

  app1:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    volumes:
      - ../file_storage:/app/file_storage
    depends_on:
      - redis

  app2:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    volumes:
      - ../file_storage:/app/file_storage
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2